package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"fmt"

	"github.com/chirag3003/collab-draw-backend/graph/model"
	"github.com/chirag3003/collab-draw-backend/internal/auth"
	"github.com/chirag3003/collab-draw-backend/internal/models"
)

// CreateProject is the resolver for the createProject field.
func (r *mutationResolver) CreateProject(ctx context.Context, input model.NewProject) (string, error) {
	authContext := auth.ForContext(ctx)
	project := &models.Project{
		Name:     input.Name,
		AppState: "",
		Elements: "",
		Owner:    authContext.Subject,
	}
	if input.Description != nil {
		project.Description = *input.Description
	}

	if input.Workspace != nil {
		workspace, err := r.Repo.Workspace.GetWorkspaceByID(ctx, *input.Workspace, authContext.Subject)
		if err != nil {
			return "", fmt.Errorf("failed to fetch workspace: %v", err)
		}
		if workspace == nil {
			return "", fmt.Errorf("workspace not found")
		}
		project.Workspace = &workspace.ID
		project.Members = workspace.Members
	}

	err := r.Repo.Project.NewProject(ctx, project)
	if err != nil {
		return "", fmt.Errorf("failed to create project: %v", err)
	}

	// Fetch the created project to broadcast to potential subscribers
	createdProject, fetchErr := r.Repo.Project.GetProjectByID(ctx, project.ID.Hex(), authContext.Subject)
	if fetchErr == nil && createdProject != nil {
		var workspace *string = nil
		if createdProject.Workspace != nil {
			hex := createdProject.Workspace.Hex()
			workspace = &hex
		}
		newProject := &model.Project{
			ID:          createdProject.ID.Hex(),
			Name:        createdProject.Name,
			Description: &createdProject.Description,
			Owner:       createdProject.Owner,
			Workspace:   workspace,
			Personal:    createdProject.Personal,
			AppState:    createdProject.AppState,
			Elements:    createdProject.Elements,
			CreatedAt:   createdProject.CreatedAt,
		}
		r.broadcastProjectUpdate(createdProject.ID.Hex(), newProject)
	}

	return "project created successfully", nil
}

// UpdateProject is the resolver for the updateProject field.
func (r *mutationResolver) UpdateProject(ctx context.Context, id string, appState string, elements string) (bool, error) {
	authContext := auth.ForContext(ctx)
	err := r.Repo.Project.UpdateProject(ctx, id, appState, elements, authContext.Subject)
	if err != nil {
		return false, fmt.Errorf("failed to update project: %v", err)
	}

	// Fetch the updated project to broadcast to subscribers
	project, err := r.Repo.Project.GetProjectByID(ctx, id, authContext.Subject)
	if err == nil && project != nil {
		var workspace *string = nil
		if project.Workspace != nil {
			hex := project.Workspace.Hex()
			workspace = &hex
		}
		updatedProject := &model.Project{
			ID:          project.ID.Hex(),
			Name:        project.Name,
			Description: &project.Description,
			Owner:       project.Owner,
			Workspace:   workspace,
			Personal:    project.Personal,
			AppState:    project.AppState,
			Elements:    project.Elements,
			CreatedAt:   project.CreatedAt,
		}
		r.broadcastProjectUpdate(id, updatedProject)
	}

	return true, nil
}

// DeleteProject is the resolver for the deleteProject field.
func (r *mutationResolver) DeleteProject(ctx context.Context, id string) (bool, error) {
	authContext := auth.ForContext(ctx)
	success, err := r.Repo.Project.DeleteProject(ctx, id, authContext.Subject)
	if err != nil {
		return false, fmt.Errorf("failed to delete project: %v", err)
	}
	return success, nil
}

// Projects is the resolver for the projects field.
func (r *queryResolver) Projects(ctx context.Context) ([]*model.Project, error) {
	projects, err := r.Repo.Project.GetAll(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to fetch projects: %v", err)
	}
	var result []*model.Project
	for _, p := range projects {
		var workspace *string = nil
		if p.Workspace != nil {
			hex := p.Workspace.Hex()
			workspace = &hex
		}
		result = append(result, &model.Project{
			ID:          p.ID.Hex(),
			Name:        p.Name,
			Description: &p.Description,
			Owner:       p.Owner,
			Workspace:   workspace,
			Personal:    p.Personal,
			AppState:    p.AppState,
			Elements:    p.Elements,
			CreatedAt:   p.CreatedAt,
		})
	}
	return result, nil
}

// Project is the resolver for the project field.
func (r *queryResolver) Project(ctx context.Context, id string) (*model.Project, error) {
	authContext := auth.ForContext(ctx)
	project, err := r.Repo.Project.GetProjectByID(ctx, id, authContext.Subject)
	if err != nil {
		return nil, fmt.Errorf("failed to fetch project: %v", err)
	}
	if project == nil {
		return nil, nil // or return an error if preferred
	}
	var workspace *string = nil
	if project.Workspace != nil {
		hex := project.Workspace.Hex()
		workspace = &hex
	}
	return &model.Project{
		ID:          project.ID.Hex(),
		Name:        project.Name,
		Description: &project.Description,
		Owner:       project.Owner,
		Workspace:   workspace,
		Personal:    project.Personal,
		AppState:    project.AppState,
		Elements:    project.Elements,
		CreatedAt:   project.CreatedAt,
	}, nil
}

// ProjectsByUser is the resolver for the projectsByUser field.
func (r *queryResolver) ProjectsByUser(ctx context.Context, userID string) ([]*model.Project, error) {
	authContext := auth.ForContext(ctx)
	projects, err := r.Repo.Project.GetProjectsByUserID(ctx, authContext.Subject)
	if err != nil {
		return nil, fmt.Errorf("failed to fetch projects: %v", err)
	}
	var result []*model.Project
	for _, p := range projects {
		var workspace *string = nil
		if p.Workspace != nil {
			hex := p.Workspace.Hex()
			workspace = &hex
		}
		result = append(result, &model.Project{
			ID:          p.ID.Hex(),
			Name:        p.Name,
			Description: &p.Description,
			Owner:       p.Owner,
			Workspace:   workspace,
			Personal:    p.Personal,
			AppState:    p.AppState,
			Elements:    p.Elements,
			CreatedAt:   p.CreatedAt,
		})
	}
	return result, nil
}

// ProjectsByWorkspace is the resolver for the projectsByWorkspace field.
func (r *queryResolver) ProjectsByWorkspace(ctx context.Context, workspaceID string) ([]*model.Project, error) {
	projects, err := r.Repo.Project.GetProjectsByWorkspaceID(ctx, workspaceID)
	if err != nil {
		return nil, fmt.Errorf("failed to fetch projects: %v", err)
	}
	var result []*model.Project
	for _, p := range projects {
		result = append(result, &model.Project{
			ID:          p.ID.Hex(),
			Name:        p.Name,
			Description: &p.Description,
			Owner:       p.Owner,
			Workspace:   &workspaceID,
			Personal:    p.Personal,
			AppState:    p.AppState,
			Elements:    p.Elements,
			CreatedAt:   p.CreatedAt,
		})
	}
	return result, nil
}

// Project is the resolver for the project field.
func (r *subscriptionResolver) Project(ctx context.Context, id string) (<-chan *model.Project, error) {
	authContext := auth.ForContext(ctx)

	// Verify user has access to this project
	project, err := r.Repo.Project.GetProjectByID(ctx, id, authContext.Subject)
	if err != nil {
		return nil, fmt.Errorf("failed to fetch project: %v", err)
	}
	if project == nil {
		return nil, fmt.Errorf("project not found or access denied")
	}

	// Create a channel for this subscription
	ch := make(chan *model.Project, 1)

	// Subscribe to project updates
	r.subscribeToProject(id, ch)

	// Send initial project state
	var workspace *string = nil
	if project.Workspace != nil {
		hex := project.Workspace.Hex()
		workspace = &hex
	}
	initialProject := &model.Project{
		ID:          project.ID.Hex(),
		Name:        project.Name,
		Description: &project.Description,
		Owner:       project.Owner,
		Workspace:   workspace,
		Personal:    project.Personal,
		AppState:    project.AppState,
		Elements:    project.Elements,
		CreatedAt:   project.CreatedAt,
	}
	ch <- initialProject

	// Clean up when context is done
	go func() {
		<-ctx.Done()
		r.unsubscribeFromProject(id, ch)
	}()

	return ch, nil
}
