package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"fmt"

	"github.com/chirag3003/collab-draw-backend/graph/model"
	"github.com/chirag3003/collab-draw-backend/internal/auth"
	"github.com/chirag3003/collab-draw-backend/internal/models"
)

// CreateWorkspace is the resolver for the createWorkspace field.
func (r *mutationResolver) CreateWorkspace(ctx context.Context, input model.NewWorkspace) (string, error) {
	authContext := auth.ForContext(ctx)
	workspace := models.Workspace{
		Name:        input.Name,
		Description: input.Description,
		Owner:       authContext.Subject,
		Members:     []string{},
	}
	err := r.Repo.Workspace.CreateWorkspace(ctx, &workspace)
	if err != nil {
		return "", fmt.Errorf("failed to create workspace: %v", err)
	}
	return "", nil
}

// DeleteWorkspace is the resolver for the deleteWorkspace field.
func (r *mutationResolver) DeleteWorkspace(ctx context.Context, id string) (bool, error) {
	authContext := auth.ForContext(ctx)
	err := r.Repo.Workspace.DeleteWorkspace(ctx, id, authContext.Subject)
	if err != nil {
		return false, fmt.Errorf("failed to delete workspace: %v", err)
	}
	return true, nil
}

// AddMemberToWorkspace is the resolver for the addMemberToWorkspace field.
func (r *mutationResolver) AddMemberToWorkspace(ctx context.Context, workspaceID string, email string) (bool, error) {
	authContext := auth.ForContext(ctx)
	workspace, err := r.Repo.Workspace.GetWorkspaceByID(ctx, workspaceID, authContext.Subject)
	if err != nil {
		return false, fmt.Errorf("failed to fetch workspace: %v", err)
	}
	if workspace == nil || workspace.Owner != authContext.Subject {
		return false, fmt.Errorf("workspace not found")
	}
	user, err := r.Repo.User.GetUserByEmail(ctx, email)
	if err != nil {
		return false, fmt.Errorf("failed to fetch user by email: %v", err)
	}
	if user == nil || len(user.Users) == 0 {
		return false, fmt.Errorf("user with email %s not found", email)
	}
	err = r.Repo.Workspace.AddMemberToWorkspace(ctx, workspaceID, user.Users[0].ID)
	if err != nil {
		return false, fmt.Errorf("failed to add member to workspace: %v", err)
	}
	return true, nil
}

// RemoveMemberFromWorkspace is the resolver for the removeMemberFromWorkspace field.
func (r *mutationResolver) RemoveMemberFromWorkspace(ctx context.Context, workspaceID string, userID string) (bool, error) {
	authContext := auth.ForContext(ctx)
	workspace, err := r.Repo.Workspace.GetWorkspaceByID(ctx, workspaceID, authContext.Subject)
	if err != nil {
		return false, fmt.Errorf("failed to fetch workspace: %v", err)
	}
	if workspace == nil || workspace.Owner != authContext.Subject {
		return false, fmt.Errorf("workspace not found")
	}
	err = r.Repo.Workspace.RemoveMemberFromWorkspace(ctx, workspaceID, userID)
	if err != nil {
		return false, fmt.Errorf("failed to remove member from workspace: %v", err)
	}
	return true, nil
}

// UpdateWorkspaceMetadata is the resolver for the updateWorkspaceMetadata field.
func (r *mutationResolver) UpdateWorkspaceMetadata(ctx context.Context, id string, name string, description string) (bool, error) {
	authContext := auth.ForContext(ctx)

	err := r.Repo.Workspace.UpdateWorkspaceMetadata(ctx, id, name, description, authContext.Subject)
	if err != nil {
		return false, fmt.Errorf("failed to update workspace metadata: %v", err)
	}
	return true, nil
}

// Workspaces is the resolver for the workspaces field.
func (r *queryResolver) Workspaces(ctx context.Context) ([]*model.Workspace, error) {
	return nil, fmt.Errorf("workspaces query is disabled")
	//workspaces, err := r.Repo.Workspace.GetAllWorkspaces(ctx)
	//if err != nil {
	//	return nil, fmt.Errorf("failed to fetch workspaces: %v", err)
	//}
	//var result []*model.Workspace
	//for _, ws := range workspaces {
	//	result = append(result, &model.Workspace{
	//		ID:          ws.ID.Hex(),
	//		Name:        ws.Name,
	//		Description: ws.Description,
	//		Owner:       ws.Owner,
	//		Members:     ws.Members,
	//		CreatedAt:   ws.CreatedAt,
	//	})
	//}
	//return result, nil
}

// Workspace is the resolver for the workspace field.
func (r *queryResolver) Workspace(ctx context.Context, id string) (*model.Workspace, error) {
	authContext := auth.ForContext(ctx)
	workspace, err := r.Repo.Workspace.GetWorkspaceByID(ctx, id, authContext.Subject)
	if err != nil {
		return nil, fmt.Errorf("failed to fetch workspace: %v", err)
	}
	if workspace == nil {
		return nil, nil // or return an error if preferred
	}
	ownerData, err := r.Repo.User.GetUsersByID(ctx, []string{workspace.Owner})
	if err != nil || ownerData == nil || len(ownerData.Users) == 0 {
		return nil, fmt.Errorf("owner not found")
	}
	owner := ownerData.Users[0]
	workspaceMembers := model.WorkspaceMembersResponse{
		Owner: &model.WorkspaceMember{
			ID:       owner.ID,
			Email:    owner.EmailAddresses[0].EmailAddress,
			FullName: *owner.FirstName + " " + *owner.LastName,
			ImageURL: *owner.ImageURL,
		},
	}

	if len(workspace.Members) != 0 {
		members, err := r.Repo.User.GetUsersByID(ctx, workspace.Members)
		if err != nil {
			return nil, fmt.Errorf("failed to fetch member details: %v", err)
		}

		for i := 0; i < len(members.Users); i++ {
			member := members.Users[i]
			workspaceMembers.Members = append(workspaceMembers.Members, &model.WorkspaceMember{
				ID:    member.ID,
				Email: member.EmailAddresses[0].EmailAddress,
				FullName: func() string {
					first := ""
					last := ""
					if member.FirstName != nil {
						first = *member.FirstName
					}
					if member.LastName != nil {
						last = *member.LastName
					}
					return first + " " + last
				}(),
				ImageURL: *member.ImageURL,
			})
		}
	}

	return &model.Workspace{
		ID:          workspace.ID.Hex(),
		Name:        workspace.Name,
		Description: workspace.Description,
		Owner:       workspace.Owner,
		CreatedAt:   workspace.CreatedAt,
		Members:     &workspaceMembers,
	}, nil
}

// WorkspacesByUser is the resolver for the workspacesByUser field.
func (r *queryResolver) WorkspacesByUser(ctx context.Context, userID string) ([]*model.Workspace, error) {
	authContext := auth.ForContext(ctx)
	workspaces, err := r.Repo.Workspace.GetWorkspacesByUser(ctx, authContext.Subject)
	if err != nil {
		return nil, fmt.Errorf("failed to fetch workspaces for user: %v", err)
	}
	var result []*model.Workspace
	for _, ws := range *workspaces {
		result = append(result, &model.Workspace{
			ID:          ws.ID.Hex(),
			Name:        ws.Name,
			Description: ws.Description,
			Owner:       ws.Owner,
			CreatedAt:   ws.CreatedAt,
		})
	}
	return result, nil
}

// SharedWorkspacesByUser is the resolver for the sharedWorkspacesByUser field.
func (r *queryResolver) SharedWorkspacesByUser(ctx context.Context, userID string) ([]*model.Workspace, error) {
	authContext := auth.ForContext(ctx)
	workspaces, err := r.Repo.Workspace.GetSharedWorkspaces(ctx, authContext.Subject)
	if err != nil {
		return nil, fmt.Errorf("failed to fetch shared workspaces for user: %v", err)
	}
	var result []*model.Workspace
	for _, ws := range *workspaces {
		result = append(result, &model.Workspace{
			ID:          ws.ID.Hex(),
			Name:        ws.Name,
			Description: ws.Description,
			Owner:       ws.Owner,
			CreatedAt:   ws.CreatedAt,
		})
	}
	return result, nil
}
