// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type NewProject struct {
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	Owner       string  `json:"owner"`
	Workspace   *string `json:"workspace,omitempty"`
	Personal    bool    `json:"personal"`
}

type NewWorkspace struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Owner       string `json:"owner"`
}

type Project struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	Owner       string  `json:"owner"`
	Workspace   *string `json:"workspace,omitempty"`
	Personal    bool    `json:"personal"`
	Elements    string  `json:"elements"`
	CreatedAt   string  `json:"createdAt"`
}

type ProjectSubscription struct {
	Elements string `json:"elements"`
	SocketID string `json:"socketID"`
}

type Query struct {
}

type Subscription struct {
}

type Workspace struct {
	ID          string                    `json:"id"`
	Name        string                    `json:"name"`
	Description string                    `json:"description"`
	Owner       string                    `json:"owner"`
	Members     *WorkspaceMembersResponse `json:"members,omitempty"`
	CreatedAt   string                    `json:"createdAt"`
}

type WorkspaceMember struct {
	ID       string `json:"id"`
	Email    string `json:"email"`
	ImageURL string `json:"imageURL"`
	FullName string `json:"fullName"`
}

type WorkspaceMembersResponse struct {
	Members []*WorkspaceMember `json:"members"`
	Owner   *WorkspaceMember   `json:"owner"`
}
