// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type NewProject struct {
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	Owner       string  `json:"owner"`
	Workspace   *string `json:"workspace,omitempty"`
	Personal    bool    `json:"personal"`
}

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type NewWorkspace struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Owner       string `json:"owner"`
}

type Project struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	Owner       string  `json:"owner"`
	Workspace   *string `json:"workspace,omitempty"`
	Personal    bool    `json:"personal"`
	AppState    string  `json:"appState"`
	Elements    string  `json:"elements"`
	CreatedAt   string  `json:"createdAt"`
}

type Query struct {
}

type Todo struct {
	ID   string `json:"id"`
	Text string `json:"text"`
	Done bool   `json:"done"`
	User *User  `json:"user"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type Workspace struct {
	ID          string   `json:"id"`
	Name        string   `json:"name"`
	Description string   `json:"description"`
	Owner       string   `json:"owner"`
	Members     []string `json:"members"`
	CreatedAt   string   `json:"createdAt"`
}
